// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOrqy7EqhVlShFPRfwpfnoV4c7EbT4O5o',
    appId: '1:723446816365:android:fb9631b7fabed2f4406964',
    messagingSenderId: '723446816365',
    projectId: 'studio-9692019390-ae379',
    storageBucket: 'studio-9692019390-ae379.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAj63G6bydOxrfHTuGSP8cNxOq_RnZjF0',
    appId: '1:723446816365:web:263aa1738e22adb1406964',
    messagingSenderId: '723446816365',
    projectId: 'studio-9692019390-ae379',
    authDomain: 'studio-9692019390-ae379.firebaseapp.com',
    storageBucket: 'studio-9692019390-ae379.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAj63G6bydOxrfHTuGSP8cNxOq_RnZjF0',
    appId: '1:723446816365:web:322ae241ecf554e6406964',
    messagingSenderId: '723446816365',
    projectId: 'studio-9692019390-ae379',
    authDomain: 'studio-9692019390-ae379.firebaseapp.com',
    storageBucket: 'studio-9692019390-ae379.firebasestorage.app',
  );

}